const fieldAccessControl = {
    1: {
        site_officer: {
            viewAccess: [
                "srNo",
                "srNoOld",
                "typeOfInv",
                "region",
                "projectDescription",
                "vendorNo",
                "vendorName",
                "gstNumber",
                "compliance206AB",
                "panStatus",
                "poCreated",
                "poNo",
                "poDate",
                "poAmt",
                "proformaInvNo",
                "proformaInvDate",
                "proformaInvAmt",
                "proformaInvRecdAtSite",
                "proformaInvRecdBy",
                "taxInvNo",
                "taxInvDate",
                "currency",
                "taxInvAmt",
                "taxInvRecdAtSite",
                "taxInvRecdBy",
                "department",
                "remarksBySiteTeam",
                "attachment",
                "qualityEngineer.dateGiven",
                "qualityEngineer.name",
                "qsMumbai.dateGiven",
                "qsMumbai.name",
                "copDetails.date",
                "copDetails.amount",
                "migoDetails.dateGiven",
                "migoDetails.no",
                "migoDetails.date",
                "migoDetails.amount",
                "migoDetails.doneBy",
                "invReturnedToSite",
                "siteEngineer.dateGiven",
                "siteEngineer.name",
                "architect.dateGiven",
                "architect.name",
                "siteIncharge.dateGiven",
                "siteIncharge.name",
                "remarks",
                "siteOfficeDispatch.dateGiven",
                "siteOfficeDispatch.name",
                "workflowState.currentState",
                "pimoMumbai.dateGiven",
                "pimoMumbai.dateReceived",
                "pimoMumbai.receivedBy",
                "qsMumbai.dateGiven",
                "qsMumbai.name",
                "pimoMumbai.namePIMO",
            ],
            editAcess: [
                "srNo",
                "srNoOld",
                "typeOfInv",
                "region",
                "projectDescription",
                "vendorNo",
                "vendorName",
                "gstNumber",
                "compliance206AB",
                "panStatus",
                "poCreated",
                "poNo",
                "poDate",
                "poAmt",
                "proformaInvNo",
                "proformaInvDate",
                "proformaInvAmt",
                "proformaInvRecdAtSite",
                "proformaInvRecdBy",
                "taxInvNo",
                "taxInvDate",
                "currency",
                "taxInvAmt",
                "taxInvRecdAtSite",
                "taxInvRecdBy",
                "department",
                "remarksBySiteTeam",
                "attachment",
                "qualityEngineer.dateGiven",
                "qualityEngineer.name",
                "qsInspection.dateGiven",
                "qsInspection.name",
                "qsCOP.name",
                "migoDetails.dateGiven",
                "migoDetails.no",
                "migoDetails.date",
                "migoDetails.amount",
                "migoDetails.doneBy",
                "invReturnedToSite",
                "siteEngineer.dateGiven",
                "siteEngineer.name",
                "architect.dateGiven",
                "architect.name",
                "siteIncharge.dateGiven",
                "siteIncharge.name",
                "remarks",
                "siteOfficeDispatch.dateGiven",
                "siteOfficeDispatch.name",
                "workflowState.currentState",
                "pimoMumbai.dateGiven",
                "pimoMumbai.dateReceived",
                "pimoMumbai.receivedBy",
                "qsMumbai.dateGiven",
            ],
        },

        quantity_survyeor: {
            viewAccess: [
                "srNo",
                "srNoOld",
                "typeOfInv",
                "region",
                "projectDescription",
                "vendorNo",
                "vendorName",
                "gstNumber",
                "compliance206AB",
                "panStatus",
                "poCreated",
                "poNo",
                "poDate",
                "poAmt",
                "proformaInvNo",
                "proformaInvDate",
                "proformaInvAmt",
                "taxInvNo",
                "taxInvDate",
                "currency",
                "taxInvAmt",
                "remarksBySiteTeam",
                "qsMumbai.dateGiven",
                "qsMumbai.name",
                "copDetails.date",
                "copDetails.amount",
                "remarks",
            ],
            editAcess: [
                "qsMesurementCheck.dateGiven",
                "vendorFinalInv.name",
                "vendorFinalInv.dateGiven",
                "qsCOP.name",
                "qsCOP.dateGiven",
                "copDetails.date",
                "copDetails.amount",
                "remarks",
            ],
        },

        pimo_mumbai: {
            viewAccess: [
                "migoDetails.dateGiven",
                "migoDetails.no",
                "migoDetails.date",
                "migoDetails.amount",
                "migoDetails.doneBy",
            ],
            editAccess: [
                "migoDetails.dateGiven",
                "migoDetails.no",
                "migoDetails.date",
                "migoDetails.amount",
                "migoDetails.doneBy",
            ],
        },

        trustees: {
            viewAccess: [
                "srNo",
                "srNoOld",
                "typeOfInv",
                "region",
                "projectDescription",
                "vendorNo",
                "vendorName",
                "gstNumber",
                "compliance206AB",
                "panStatus",
                "poCreated",
                "poNo",
                "poDate",
                "poAmt",
                "proformaInvNo",
                "proformaInvDate",
                "proformaInvAmt",
                "proformaInvRecdAtSite",
                "proformaInvRecdBy",
                "taxInvNo",
                "taxInvDate",
                "currency",
                "taxInvAmt",
                "taxInvRecdAtSite",
                "taxInvRecdBy",
                "department",
                "remarksBySiteTeam",
                "attachment",
                "qualityEngineer.dateGiven",
                "qualityEngineer.name",
                "qsMumbai.dateGiven",
                "qsMumbai.name",
                "copDetails.date",
                "copDetails.amount",
                "migoDetails.dateGiven",
                "migoDetails.no",
                "migoDetails.date",
                "migoDetails.amount",
                "migoDetails.doneBy",
                "invReturnedToSite",
                "siteEngineer.dateGiven",
                "siteEngineer.name",
                "architect.dateGiven",
                "architect.name",
                "siteIncharge.dateGiven",
                "siteIncharge.name",
                "remarks",
                "siteOfficeDispatch.dateGiven",
                "siteOfficeDispatch.name",
                "workflowState.currentState",
                "pimoMumbai.dateGiven",
                "pimoMumbai.dateReceived",
                "pimoMumbai.receivedBy",
                "qsMumbai.dateGiven",
                "qsMumbai.name",
                "pimoMumbai.namePIMO",
            ],
            editAccess: [],
        },

        accounts: {
            viewAccess: [
                "srNo",
                "srNoOld",
                "typeOfInv",
                "region",
                "projectDescription",
                "vendorNo",
                "vendorName",
                "gstNumber",
                "compliance206AB",
                "panStatus",
                "poCreated",
                "poNo",
                "poDate",
                "poAmt",
                "proformaInvNo",
                "proformaInvDate",
                "proformaInvAmt",
                "proformaInvRecdAtSite",
                "proformaInvRecdBy",
                "taxInvNo",
                "taxInvDate",
                "currency",
                "taxInvAmt",
                "taxInvRecdAtSite",
                "taxInvRecdBy",
                "department",
                "remarksBySiteTeam",
                "attachment",
                "copDetails.amount",
                "pimoMumbai.dateGiven",
                "pimoMumbai.dateReceived",
            ],
            editAccess: [],
        },
    },

    2: {
        site_officer: {
            viewAccess: [],
            editAccess: [],
        },
        quantity_survyeor: {
            viewAccess: ["qsMumbai.dateGiven", "qsMumbai.name"],
            editAccess: [],
        },
        pimo_mumbai: {
            viewAccess: [
                "pimoMumbai.dateReceived",
                "pimoMumbai.receivedBy",
                "qsMumbai.dateGiven",
                "qsMumbai.name",
                "",
            ],
            editAccess: [
                "pimoMumbai.dateReceived",
                "pimoMumbai.receivedBy",
                "qsMumbai.dateGiven",
                "qsMumbai.name",
            ],
        },
        trustees: {
            viewAccess: ["pimoMumbai.dateReceived", "pimoMumbai.receivedBy"],
            editAccess: [],
        },
        accounts: {
            viewAccess: [],
            editAccess: [],
        },
    },
    3: {
        site_officer: {
            viewAccess: [],
            editAccess: [],
        },
        quantity_survyeor: {
            viewAccess: ["pimoMumbai.dateGivenPIMO", "pimoMumbai.namePIMO"],
            editAccess: ["pimoMumbai.dateGivenPIMO", "pimoMumbai.namePIMO"],
        },
        pimo_mumbai: {
            viewAccess: ["pimoMumbai.dateGivenPIMO", "pimoMumbai.namePIMO"],
            editAccess: ["pimoMumbai.dateGivenPIMO"],
        },
        trustee: {
            viewAccess: ["pimoMumbai.dateGivenPIMO", "pimoMumbai.namePIMO"],
            editAccess: [],
        },
        accounts: {
            viewAccess: [],
            editAccess: [],
        },
    },
    4: {
        site_officer: {
            viewAccess: [],
            editAccess: [],
        },
        quantity_surveyor: {
            viewAccess: [],
            editAccess: [],
        },
        pimo_mumbai: {
            viewAccess: [
                "itDept.dateGiven",
                "itDept.name",
                "itDept.dateReceived",
                "sesDeatils.no",
                "sesDetails.date",
                "sesDetails.amount",
                "sesDetails.doneBy",
                "pimoMumbai.dateGivenPIMO2",
                "pimoMumbai.namePIMO2",
                "pimoMumbao.dateReceivedFromIT",
                "pimoMumbai.dateReceivedFromPIMO",
            ],
            editAccess: [
                "itDept.dateGiven",
                "itDept.name",
                "itDept.dateReceived",
                "sesDeatils.no",
                "sesDetails.date",
                "sesDetails.amount",
                "sesDetails.doneBy",
                "pimoMumbai.dateGivenPIMO2",
                "pimoMumbai.namePIMO2",
                "pimoMumbao.dateReceivedFromIT",
                "pimoMumbai.dateReceivedFromPIMO",
            ],
        },
        trustees: {
            viewAccess: [
                "itDept.dateGiven",
                "itDept.name",
                "itDept.dateReceived",
                "sesDeatils.no",
                "sesDetails.date",
                "sesDetails.amount",
                "sesDetails.doneBy",
                "pimoMumbai.dateGivenPIMO2",
                "pimoMumbai.namePIMO2",
                "pimoMumbao.dateReceivedFromIT",
                "pimoMumbai.dateReceivedFromPIMO",
            ],
            editAccess: [],
        },
        accounts: {
            viewAccess: [],
            editAccess: [],
        },
    },
    5: {
        site_officer: {
            viewAccess: [],
            editAccess: [],
        },
        quantity_survyeor: {
            viewAccess: [],
            editAccess: [],
        },
        pimo_mumbai: {
            viewAccess: [],
            editAccess: [],
        },
        trustees: {
            viewAccess: ["approvalDetails.directorApproval.dateGiven"],
            editAccess: ["approvalDetails.directorApproval.dateGiven"],
        },
        accounts: {
            viewAccess: [],
            editAccess: [],
        },
    },
    6: {
        site_officer: {
            viewAccess: [],
            editAccess: [],
        },
        quantity_survyeor: {
            viewAccess: [],
            editAccess: [],
        },
        pimo_mumbai: {
            viewAccess: [
                "approvalDetails.directorApproval.dateReceived",
                "approvalDetails.remarksPimoMumbai",
                "accountsDept.dateGiven",
                "accountsDept.givenBy",
            ],
            editAccess: [
                "approvalDetails.directorApproval.dateReceived",
                "approvalDetails.remarksPimoMumbai",
                "accountsDept.dateGiven",
                "accountsDept.givenBy",
            ],
        },
        trustees: {
            viewAccess: [
                "approvalDetails.directorApproval.dateReceived",
                "approvalDetails.remarksPimoMumbai",
                "accountsDept.dateGiven",
                "accountsDept.givenBy",
            ],
            editAccess: [],
        },
        accounts: {
            viewAccess: [
                "approvalDetails.remarksPimoMumbai",
                "accountsDept.dateGiven",
                "accountsDept.givenBy",
            ],
        },
    },
    7: {
        site_officer: {
            viewAccess: [],
            editAccess: [],
        },
        quantity_survyeor: {
            viewAccess: [],
            editAccess: [],
        },
        pimo_mumbai: {
            viewAccess: [
                "accountsDept.dateReceived",
                "accountsDept.receivedBy",
                "accountsDept.returnedToPIMO",
                "accountsDept.revceivedBack",
                "accountsDept.remarkForPayInstructions",
                "accountsDept.f110Identification",
                "accountsDept.paymentDate",
                "accountsDept.accountsIndentification",
                "accountsDept.paymentyAmt",
                "accountsDept.status",
            ],
            editAccess: [],
        },
        accounts: {
            viewAccess: [
                "accountsDept.dateReceived",
                "accountsDept.receivedBy",
                "accountsDept.returnedToPIMO",
                "accountsDept.revceivedBack",
                "accountsDept.paymentInstructions",
                "accountsDept.remarkForPayInstructions",
                "accountsDept.f110Identification",
                "accountsDept.paymentDate",
                "accountsDept.accountsIndentification",
                "accountsDept.paymentyAmt",
                "accountsDept.remarksAcctsDept",
                "accountsDept.status",
            ],
            editAccess: [
                "accountsDept.dateReceived",
                "accountsDept.receivedBy",
                "accountsDept.returnedToPIMO",
                "accountsDept.revceivedBack",
                "accountsDept.paymentInstructions",
                "accountsDept.f110Identification",
                "accountsDept.paymentDate",
                "accountsDept.accountsIndentification",
                "accountsDept.paymentyAmt",
                "accountsDept.remarksAcctsDept",
                "accountsDept.status",
            ],
        },
        trustees: {
            viewAccess: [
                "accountsDept.dateReceived",
                "accountsDept.receivedBy",
                "accountsDept.returnedToPIMO",
                "accountsDept.revceivedBack",
                "accountsDept.paymentInstructions",
                "accountsDept.remarkForPayInstructions",
                "accountsDept.f110Identification",
                "accountsDept.paymentDate",
                "accountsDept.accountsIndentification",
                "accountsDept.paymentyAmt",
                "accountsDept.remarksAcctsDept",
                "accountsDept.status",
            ],
            editAccess: [
                "accountsDept.paymentInstructions",
                "accountsDept.remarkForPayInstructions",
            ],
        },
    },
};
